### ISSUE TITLE
Explained installation steps?

### ISSUE THREAD

**Issue by n1kh1l1337** [Zelig880/BooksBank#42]

**Comment by Zelig880** [comment]
Hi, Would you please be able to explain what information you require? 

if you tell me where you got stuck (if anywhere) I will be happy to add more informaiton to the readme to explain the installation process further (there are already information at the bottom of the readme)

**Comment by n1kh1l1337** [comment]
I followed up the readme part and when i do the npm run watch it just shows me blank page the modules doesnt seem to load

**Comment by Zelig880** [comment]
Hi @n1kh1l1337 ! Just to let you know the issue you were encounting has been solved now!!

It was due to a vue-router minor release that was breaking the Frontnend!

if you try again (use yarn is prefeered), then let me know how it goes. Also if you want to have a chat about stories or any other info, join the slack channel! (link in the readme)
